SELECT 'Clientes' AS tabla, COUNT(*) AS num_registros FROM CLIENTES
UNION ALL
SELECT 'Categorias', COUNT(*) FROM CATEGORIAS
UNION ALL
SELECT 'Productos', COUNT(*) FROM PRODUCTOS
UNION ALL
SELECT 'Pedidos', COUNT(*) FROM PEDIDOS
UNION ALL
SELECT 'Lineas_Pedidos', COUNT(*) FROM LINEAS_PEDIDOS;